name: Build
on:
    push:
permissions:
    contents: write
jobs:
    build:
        concurrency: ci-${{ github.ref }}

        strategy:
            fail-fast: false
            matrix:
                node: ["18.7.0"]
                arch: ["arm64"]
                sdk: ["26"]

        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Install dependencies
              run: |
                  sudo apt-get install python3 g++ make python3-pip

            - name: "Install android ndk"
              uses: nttld/setup-ndk@v1
              id: setup-ndk
              with:
                  ndk-version: r25
                  add-to-path: false

            - name: "Clone node"
              run: |
                  curl -RLO https://nodejs.org/dist/v${{ matrix.node }}/node-v${{ matrix.node }}.tar.xz
                  tar xJf node-v${{ matrix.node }}.tar.xz

            - name: "Configure"
              working-directory: ./node-v${{ matrix.node }}
              run: |
                  ./android-configure ${{ steps.setup-ndk.outputs.ndk-path }} ${{ matrix.arch }} ${{ matrix.sdk }}

                  sed -i 's|/poll.o \\|/poll.o \\\n\t$(obj).target/$(TARGET)/deps/uv/src/unix/epoll.o \\|' out/deps/uv/libuv.target.mk
                  sed -i "s|// Setup for shared library export.|#undef V8_TRAP_HANDLER_VIA_SIMULATOR\n#undef V8_TRAP_HANDLER_SUPPORTED\n#define V8_TRAP_HANDLER_SUPPORTED false\n\n// Setup for shared library export.|" deps/v8/src/trap-handler/trap-handler.h

            - name: "Build"
              working-directory: ./node-v${{ matrix.node }}
              run: |
                  make -j4
