name: Build
on:
    push:
permissions:
    contents: write
jobs:
    build-node-v16:
        strategy:
            fail-fast: false
            matrix:
                node: ["16.16.0"]
                arch: ["arm64", "x86_64"]
                sdk: [21, 22, 23, 24, 26, 27, 28, 29, 30, 31, 32, 33]

        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Install dependencies
              run: |
                  sudo apt-get install python3 gcc g++ make python3-pip gcc-multilib g++-multilib

            - name: "Install android ndk"
              uses: nttld/setup-ndk@v1
              id: setup-ndk
              with:
                  ndk-version: r25
                  add-to-path: false

            - name: "Clone node"
              run: |
                  curl -RLO https://nodejs.org/dist/v${{ matrix.node }}/node-v${{ matrix.node }}.tar.xz
                  tar xJf node-v${{ matrix.node }}.tar.xz

            - name: "Configure"
              run: |
                  cp ./android-configure ./node-v${{ matrix.node }}/android-configure
                  cd ./node-v${{ matrix.node }}
                  chmod +x ./android-configure
                  ./android-configure ${{ steps.setup-ndk.outputs.ndk-path }} ${{ matrix.arch }} ${{ matrix.sdk }}

            - name: "Build"
              working-directory: ./node-v${{ matrix.node }}
              run: |
                  make -j4

            - name: "Rename build output"
              run: |
                  mv ./node-v${{ matrix.node }}/out/Release/libnode.so ./node-v${{ matrix.node }}/out/Release/libnode-v${{ matrix.node }}-${{ matrix.arch }}-sdk-${{ matrix.sdk }}.so

            - name: "Upload build"
              uses: actions/upload-artifact@v3
              with:
                  name: libnode-v${{ matrix.node }}-${{ matrix.arch }}-sdk-${{ matrix.sdk }}
                  path: ./node-v${{ matrix.node }}/out/Release/libnode-v${{ matrix.node }}-${{ matrix.arch }}-sdk-${{ matrix.sdk }}.so
